config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'inventories#research_index'
  get '/activity_introduction' => 'welcome#activity_introduction'
  get '/research' => 'register#research_index'
  get '/abid_research' => 'inventories#research_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    post 'json_users', on: :collection
    post 'lottery', on: :collection
    get 'delete', on: :collection
    get 'active', on: :collection
    get 'reset', on: :collection
    post 'admin_create', on: :collection
    get 'research', on: :collection
  end

  resources :activitys do
    get 'delete', on: :collection
  end

  resources :user_lists do
    get :leader_index,   on: :collection
    get :import,         on: :collection
    post :upload, on: :collection
    get :import_preview, on: :collection
  end
  resources :register

  resources :user_requests
  resources :request_stats

  resources :welcome do
    get :scan_code,   on: :collection
  end
  resources :draw
  resources :signin
  post '/register/upload_img' => 'register#upload_img'

  get '/home/qrcode' => 'home#qrcode'
  post '/home/upload_register' => 'home#upload_register'
  post '/home/upload_signin' => 'home#upload_signin'

  resources :inventories do
    get :research, on: :collection
    post :upload, on: :collection
  end

  resources :fridges
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true  #这几个不能为空
  validates :name, length: { in: 2..25 } #设备名长度6-25
	#validates :attendance,  uniqueness: { case_sensitive: false }#工号必须唯一
  belongs_to :user_list
  has_many :families, dependent: :destroy
  after_create :sent_msg #发送报名通知

  def self.signin_count
    where(is_active: true).count
  end

  def self.to_xlsx(records)
    # export_fields = ["name", "is_attendance", "is_lunch", "phone", "id_number", "is_car", "notes"]
    # export_fields = ["name", "is_car"]
    export_fields = ["name", "is_attendance", "is_car", "id_number", "phone", "family_type", "height", "notes", "leader_id", "gsyg"]
    SpreadsheetService.new.generate(export_fields, records)
  end

  def sent_msg
    # NotificationMailer.register_msg(self).deliver
    # system("/usr/bin/python3 /var/www/usms.py #{phone} #{id}")
  end

  def family_type
    "公司员工"
  end

  def height
  end

  def leader_id
    user_list.try(:leader_name)
  end

  def gsyg
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'template'
  http_basic_authenticate_with name: "yk_labour_union", password: "YKgonghui!123?", only: :index

  def index
    @users = User.all.paginate page: params[:page], per_page: 18

    respond_to { |format|
      format.html
      format.json { render json: @users}
      format.xlsx { send_data User.to_xlsx(User.all).stream.string, filename: "报名名单.xlsx", disposition: 'attachment' }
    }
  end

  def admin_create
    @user = User.new
    @user.name = params[:user][:username]
    @user.attendance = params[:user][:attendance]
    @user.avatar_url = "/default_avatar-thumb.jpg"
    @user.pre = params[:user][:pre]
    @user.phone = params[:user][:phone]
    @user.year =  Date.today.year
    @user.is_active = 1
    @user.save
    if @user.save
      flash["success"] = "添加成功"
    else
      flash["danger"] = "添加失败"
    end
    redirect_to users_url
  end

  def delete
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_path
  end

  def active
    @user = User.find params[:id]
    @user.is_active = 1
    @user.save
    redirect_to users_path
  end

  def reset
    User.update_all(lottery:nil)
    redirect_to users_url
  end

  def research
    @user = User.find_by_name_and_id(params[:post][:username],params[:post][:user_id])
  end

  def json_users
    @users = User.where(is_active: true)
    render json: {info:@users}
  end

  def lottery
    @user = User.find_by_phone params[:phone]
    @user.lottery = params[:lottery]
    @user.save
    render json: {code: 1,info: ''}
  end
end

app/views/users/edit.html.erb
<% provide :c_active, "user_lists" %>
<%= render 'shared/navigation' %>
<br/>
<div class="uk-panel uk-panel-box">
  <%= form_for @user, html: { class: "uk-form uk-form-stacked" } do |f| %>
    <div class="uk-form-row">
      <label class="uk-form-label" for="">姓名<span style="color:red;">*</span></label>
      <div class="uk-form-controls">
        <input type="text" id="username" value="<%= @user.name %>" name="post[username]" class="uk-width-1-1" placeholder="请输入您的真实姓名">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">年龄<span style="color:red;">*</span></label>
      <div class="uk-form-controls">
        <input type="number" id="age" value="<%= @user.age %>" name="post[age]" class="uk-width-1-1" placeholder="请输入您的年龄">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">性别<span style="color:red;">*</span></label>
      <div class="uk-form-controls">
         <span class="id-pre uk-width-1-1">
           <select id="pre" name="post[pre]">
             <option value="男" <%= 'selected="selected"' if @user.pre == '男' %>>男</option>
             <option value="女" <%= 'selected="selected"' if @user.pre == '女' %>>女</option>
          </select>
         </span>
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">手机号码<span style="color:red;">*</span></label>
      <div class="uk-form-controls">
        <input type="number" id="phone" value="<%= @user.phone %>" name="post[phone]" class="uk-width-1-1" placeholder="请输入您的手机号码">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">学历</label>
      <div class="uk-form-controls">
        <input type="text" id="attendance" value="<%= @user.attendance %>" name="post[attendance]" class="uk-width-1-1" placeholder="请输入您的学历">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">爱好</label>
      <div class="uk-form-controls">
        <textarea id="notes" cols="30" rows="5" placeholder="请输入您的兴趣爱好" class="uk-width-1-1" name="post[notes]"><%= @user.notes %></textarea>
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="btn_submit">
      <a class="uk-button uk-button-primary" href="/users">返回</a>
      <button class="uk-button uk-button-primary uk-margin-left" id="btn_submit" type="submit">保存</button>
      </label>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide :c_active, "users" %>
<%= render 'shared/navigation' %>

<!-- 添加弹框 -->
<div class="uk-alert" data-uk-alert="">
  <button class="uk-button uk-button-primary uk-margin-left" data-uk-modal="{target:'#create'}">添加</button>
  <a class="uk-button uk-button-primary uk-margin-left" href="/users.xlsx">全员名单</a>
</div>
<div id="create" class="uk-modal" aria-hidden="true" style="display: none; overflow-y: scroll;">
  <div class="uk-modal-dialog">
    <button type="button" class="uk-modal-close uk-close"></button>
    <div class="uk-modal-header">
      <h2>添加</h2>
    </div>
    <%= form_for User.new, url: admin_create_users_path do |f| %>
      <div>
        <div class="uk-margin-small-top uk-modal-content uk-form">
          <div class="uk-form-row">
            <label class="uk-form-label" for="">工牌号:</label>
            <div class="uk-form-controls">
              <span class="id-pre uk-width-1-5">
                <select id="pre" name="user[pre]">
                  <option value="YKSW-">YKSW-</option>
                  <option value="XXX-">XXX-</option>
                </select>
              </span>
              <input type="number" id="id" value="" name="user[attendance]" class="uk-width-4-5" placeholder="请输入工牌号码">
            </div>
          </div>
          <div class="uk-form-row">
            <label class="uk-form-label" for="">姓名:</label>
            <div class="uk-form-controls">
              <input type="text" id="username" value="" name="user[username]" class="uk-width-1-1" placeholder="请输入你的真实姓名">
            </div>
          </div>
          <div class="uk-form-row">
            <label class="uk-form-label" for="">手机号码:</label>
            <div class="uk-form-controls">
              <input type="number" id="phone" value="" name="user[phone]" class="uk-width-1-1" placeholder="请输入你的手机号码">
            </div>
          </div>
        </div>
      </div>
      <div class="uk-modal-footer uk-text-right">
        <button type="button" class="uk-button uk-modal-close">Cancel</button>
        <button type="submit" class="uk-button uk-button-primary">Save</button>
      </div>
    <% end %>
  </div>
</div>

<% if @users.present? %>
  <table class="uk-table uk-table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>姓名</th>
        <th>联系方式</th>
        <th>身份证号</th>
        <th>路线选择</th>
        <th>备注</th>
        <th>家属</th>
        <!--
        <th>车型/颜色</th>
        <th>车牌号</th>
        <th>缴费周期</th>
        <th>是否参与摇号</th>
        -->
        <!--<th>备注</th>-->
        <th>删除</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr <%= "class=uk-form-danger" if user.is_car == "有事不能参加, 很遗憾T_T" %> >
      	<td><%= user.id %></td>
      	<td><%= user.name %></td>
        <td><%= user.phone %></td>
      	<td><%= user.id_number %></td>
      	<td><%= user.is_car %></td>
      	<td><%= user.notes %></td>

        <!--
      	<td><%#= user.is_lunch %></td>
      	<td><%#= user.is_attendance %></td>
      	<td><%#= user.phone %></td>
        <td><%#= user.id_number %></td>
        -->
        <td>
          <% user.families.each do |family| %>
            姓名:<%= family.name %>, 类型:<%= family.family_type %><%if family.family_type != '成人'%>, 身高:<%= family.height %><%end%>, 身份证号:<%= family.id_number %> <br>
          <% end %>
        </td>
        <!--<td><%#= user.notes %></td>-->
      	<td><a href="/users/delete?id=<%=user.id%>">删除</a></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @users, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
<% end %>

app/views/users/research.html.erb
<div class="register-box">
  <h1 class="title">登记结果</h1>
    <% if @user.present? %>
      <div class="uk-form-row">
        <label style="font-weight: bold;">姓名: </label> <%= @user.name %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">联系方式: </label> <%= @user.phone %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">身份证号: </label> <%= @user.id_number %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">路线选择: </label> <%= @user.is_car %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">备注: </label> <%= @user.notes %>
      </div>
      <!--
      <div class="uk-form-row">
        <label style="font-weight: bold;">车型/颜色: </label> <%#= @user.is_lunch %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">车牌号: </label> <%#= @user.id_number %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">缴费周期: </label> <%#= @user.is_car %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">是否参与摇号: </label> <%#= @user.is_attendance %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">直属领导: </label> <%#= @user.is_lunch %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">联系方式: </label> <%#= @user.phone %>
      </div>
      -->
      <!--
      <div class="uk-form-row">
        <label style="font-weight: bold;">车型/颜色: </label> <%#= @user.is_lunch %>
      </div>
      <div class="uk-form-row">
        <label style="font-weight: bold;">是否参加: </label> <%#= @user.is_car %>
      </div>
      -->



      <% if @user.families.present? %>
        <h3 class="tm-article-subtitle">家属</h3>
      <% end %>
      <div class="uk-form-row families-div">
        <% @user.families.each do |family| %>
          <ul class="uk-list">
            <li><label style="font-weight: bold;">姓名: </label> <%= family.name %>(<%= family.family_type %>)</li>
            <li><label style="font-weight: bold;">身高: </label> <%= family.height %></li>
            <li><label style="font-weight: bold;">身份证号: </label> <%= family.id_number %></li>
          </ul>
        <% end %>
      </div>
    <% else %>
      姓名和ID不匹配，查询失败
    <% end %>

</div>
<style type="text/css" media="screen">
  .tm-article-subtitle {
    padding-left: 6px;
    border-left: 3px solid #1FA2D6;
    font-size: 16px;
    line-height: 16px;
  }
</style>