config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'inventories#research_index'
  get '/activity_introduction' => 'welcome#activity_introduction'
  get '/research' => 'register#research_index'
  get '/abid_research' => 'inventories#research_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    post 'json_users', on: :collection
    post 'lottery', on: :collection
    get 'delete', on: :collection
    get 'active', on: :collection
    get 'reset', on: :collection
    post 'admin_create', on: :collection
    get 'research', on: :collection
  end

  resources :activitys do
    get 'delete', on: :collection
  end

  resources :user_lists do
    get :leader_index,   on: :collection
    get :import,         on: :collection
    post :upload, on: :collection
    get :import_preview, on: :collection
  end
  resources :register

  resources :user_requests
  resources :request_stats

  resources :welcome do
    get :scan_code,   on: :collection
  end
  resources :draw
  resources :signin
  post '/register/upload_img' => 'register#upload_img'

  get '/home/qrcode' => 'home#qrcode'
  post '/home/upload_register' => 'home#upload_register'
  post '/home/upload_signin' => 'home#upload_signin'

  resources :inventories do
    get :research, on: :collection
    post :upload, on: :collection
  end

  resources :fridges
end

app/models/user_request.rb
class UserRequest < ApplicationRecord
  after_create :async_flush_request_stats

  def path
    return read_attribute(:path) if read_attribute(:path).present?

    URI.parse(url).path
  end

  def params
    return read_attribute(:params) if read_attribute(:params).present?

    uri = URI.parse url
    CGI.parse(uri.query).reject{|_, v| v.reject(&:empty?).empty?} if uri.query
  end

  private

  def async_flush_request_stats
    flush_request_stats
  end

  def flush_request_stats
    request_stat = RequestStat.where(path: path).first

    if request_stat
      request_stat.count += 1
      request_stat.max_time = [time, request_stat.max_time].max
      request_stat.min_time = [time, request_stat.min_time].min
      request_stat.last_requested_at = created_at
      request_stat.avg_time = UserRequest.where(request_stat_id: request_stat.id).average(:time)
    else
      request_stat = RequestStat.create(
        path: path,
        count: 1,
        max_time: time,
        min_time: time,
        last_requested_at: created_at,
        avg_time: time
      )
    end

    update_attributes request_stat_id: request_stat.id

    params_stats = JSON.parse(request_stat.params_stats || "{}")

    JSON.parse(params).reject{|_, v| !v.present?}.each do |item|
      if item[1].is_a?(Hash)
        item[1].reject{|_, v| !v.present?}.keys.each do |item_key|
          next if item_key.match(/attachment/)
          new_key = "#{item[0]}[#{item_key}]".gsub(/_\d+/, '_#{id}')
          if params_stats.keys.include?(new_key)
            params_stats[new_key] += 1
          else
            params_stats[new_key] = 1
          end
        end
      else
        next if item[0].match(/attachment/)
        new_key = item[0].gsub(/_\d+/, '_#{id}')
        if params_stats.keys.include?(new_key)
          params_stats[new_key] += 1
        else
          params_stats[new_key] = 1
        end
      end
    end

    request_stat.params_stats = JSON[params_stats]
    request_stat.save!
  end
end

app/controllers/user_requests_controller.rb
class UserRequestsController < ApplicationController
  layout 'template'
  http_basic_authenticate_with name: "yk_labour_union", password: "YKgonghui!123?"

  def index
    @user_requests = UserRequest.all.paginate page: params[:page], per_page: 18
  end
end

app/views/user_requests/index.html.erb
<% provide :c_active, "home" %>
<%= render 'shared/navigation' %>

<% flash.each do |name, msg| %>
  <div class="uk-alert uk-alert-<%= name %>" data-uk-alert="">
    <a href="" class="uk-alert-close uk-close"></a>
    <p><%= msg %></p>
  </div>
<% end %>

<% if @user_requests.present? %>
<table class="uk-table uk-table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>URL</th>
      <th>Time</th>
      <th>path</th>
      <th>remote_ip</th>
      <th>params</th>
      <th>create</th>
      <th>update</th>
      <th>操作</th>
    </tr>
  </thead>
  <% @user_requests.each do |user_request| %>
      <tr>
        <td><%= user_request.id %></td>
        <td><%= user_request.url %></td>
        <td><%= user_request.time %></td>
        <td><%= user_request.path %></td>
        <td><%= user_request.remote_ip %></td>
        <td><%= user_request.params %></td>
        <td><%= user_request.created_at %></td>
        <td><%= user_request.updated_at %></td>
      	<td><%= link_to '删除', user_request_path(user_request), method: :delete, data: { confirm: '你确定要删除吗?' } %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @user_requests, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
<% end %>