config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'inventories#research_index'
  get '/activity_introduction' => 'welcome#activity_introduction'
  get '/research' => 'register#research_index'
  get '/abid_research' => 'inventories#research_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    post 'json_users', on: :collection
    post 'lottery', on: :collection
    get 'delete', on: :collection
    get 'active', on: :collection
    get 'reset', on: :collection
    post 'admin_create', on: :collection
    get 'research', on: :collection
  end

  resources :activitys do
    get 'delete', on: :collection
  end

  resources :user_lists do
    get :leader_index,   on: :collection
    get :import,         on: :collection
    post :upload, on: :collection
    get :import_preview, on: :collection
  end
  resources :register

  resources :user_requests
  resources :request_stats

  resources :welcome do
    get :scan_code,   on: :collection
  end
  resources :draw
  resources :signin
  post '/register/upload_img' => 'register#upload_img'

  get '/home/qrcode' => 'home#qrcode'
  post '/home/upload_register' => 'home#upload_register'
  post '/home/upload_signin' => 'home#upload_signin'

  resources :inventories do
    get :research, on: :collection
    post :upload, on: :collection
  end

  resources :fridges
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  layout 'template'
  def index
  end

  def create
    if check_phone(params[:post][:phone])
      @user = User.find_by_phone params[:post][:phone]
      @user.is_active = 1
      if @user.save
        # ActionCable.server.broadcast 'signin', message: {user_info: @user, signin_count: User.signin_count}
        redirect_to "/welcome?active=1&_id=#{@user.id}"
      else
        '没有找到此用户'
        redirect_to signin_index_url
      end
    else
      '没有找到此用户'
      redirect_to signin_index_url
    end
  end

  private
    def check_phone(phone)
      count = User.where(phone: phone).count
      return count == 1
    end
end

app/views/signin/index.html.erb
<div class="register-box">
  <h1 class="title"><%= @web_config["web_name"] %></h1>
  <h2 class="title">激活我的帐号</h1>
    <%= form_for :signin, url: signin_index_path, method: :post, html: { class: "uk-form uk-form-stacked" } do |f| %>
      <div class="uk-form-row">
        <label class="uk-form-label" for="">手机号码</label>
        <div class="uk-form-controls">
          <input type="number" id="phone" name="post[phone]" class="uk-width-1-1" placeholder="请输入你的手机号码">
        </div>
      </div>
      <div class="uk-form-row">
        <label class="uk-form-label" for="">
          <button class="uk-button" id="btn_submit" type="submit">提交，激活</button>
        </label>
      </div>
    <% end %>
</div>