config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root 'inventories#research_index'
  get '/activity_introduction' => 'welcome#activity_introduction'
  get '/research' => 'register#research_index'
  get '/abid_research' => 'inventories#research_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    post 'json_users', on: :collection
    post 'lottery', on: :collection
    get 'delete', on: :collection
    get 'active', on: :collection
    get 'reset', on: :collection
    post 'admin_create', on: :collection
    get 'research', on: :collection
  end

  resources :activitys do
    get 'delete', on: :collection
  end

  resources :user_lists do
    get :leader_index,   on: :collection
    get :import,         on: :collection
    post :upload, on: :collection
    get :import_preview, on: :collection
  end
  resources :register

  resources :user_requests
  resources :request_stats

  resources :welcome do
    get :scan_code,   on: :collection
  end
  resources :draw
  resources :signin
  post '/register/upload_img' => 'register#upload_img'

  get '/home/qrcode' => 'home#qrcode'
  post '/home/upload_register' => 'home#upload_register'
  post '/home/upload_signin' => 'home#upload_signin'

  resources :inventories do
    get :research, on: :collection
    post :upload, on: :collection
  end

  resources :fridges
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  layout 'template'
  before_action :check_params, only: [:create]
  before_action :check_attenance, only: [:create]

  def index
    @user = User.new
  end

  def research_index

  end

  def create
    if check_user(yk_user(:username))
      create_user
      redirect_to welcome_index_url(_id: @user.id)
    else
      redirect_to register_index_url
    end

  end

  def create_user
    @user = User.new
    @user.name = params[:post][:username]
    @user.is_attendance = params[:post][:is_attendance]
    @user.is_car = params[:post][:is_car]
    @user.is_lunch = params[:post][:is_lunch]
    @user.id_number = params[:post][:id_number]
    @user.phone = params[:post][:phone]
    @user.notes = params[:post][:notes]
    @user.user_list = UserList.find_by_name params[:post][:username]
    @user.save

    families = params[:post][:families]
    if families.present?
      families.each do |people|
        if people[:name].present?
          @user.families.create(name: people[:name], family_type: people[:type], id_number: people[:id_number], height: people[:height])
        end
      end
    end
  end

  private
    def check_params
      if params[:post].present? && params[:post][:username].present?
        return true
      else
        flash["danger"] = "参数缺失，注册失败"
        redirect_to register_index_url
      end
    end

    def check_attenance
      if params[:post].blank? || params[:post][:is_car].blank?
        flash["danger"] = "参数缺失，注册失败"
        redirect_to register_index_url
      elsif params[:post][:is_car] == "有事不能参加, 很遗憾T_T"
        return true
      else
        if User.where(is_car: params[:post][:is_car]).count >= 1800
          flash["danger"] = "剩余座席不足，注册失败"
          redirect_to register_index_url
        else
          return true
        end
      end
    end

    def yk_user(key)
      params[:post][key]
    end

    def check_user(username)
      if UserList.find_by_name(username).blank?
        flash["danger"] = "该员工#{username}不存在！"
        return nil
      end

      if User.find_by_name(username).present?
        flash["danger"] = "该员工#{username}已登记,请勿重复操作！"
        return nil
      end

      return true
    end

    def check_phone(phone)
      if User.find_by_phone(phone).present?
        flash["danger"] = "该电话号码#{phone}已注册！"
        return nil
      end
      return true
    end

end

app/views/register/index.html.erb
<% flash.each do |name, msg| %>
  <div class="uk-alert uk-alert-<%= name %>" data-uk-alert="">
    <a href="" class="uk-alert-close uk-close"></a>
    <p><%= msg %></p>
  </div>
<% end %>
<div class="register-box">
  <h1 class="title">请填写以下信息</h1>
  <%= form_for :register, url: register_index_path, method: :post, html: { class: "uk-form uk-form-stacked" } do |f| %>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">姓名</label>
      <div class="uk-form-controls">
        <input type="text" id="username" value="" name="post[username]" class="uk-width-1-1" placeholder="请输入你的真实姓名">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">手机号码</label>
      <div class="uk-form-controls">
        <input type="number" id="phone" value="" name="post[phone]" class="uk-width-1-1" placeholder="请输入你的手机号码">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">身份证号</label>
      <div class="uk-form-controls">
        <input type="text" id="id_number" value="" name="post[id_number]" class="uk-width-1-1" placeholder="身份证号，请认真填写">
      </div>
    </div>
<!--
    <div class="uk-form-row">
      <label class="uk-form-label" for="">车型/颜色</label>
      <div class="uk-form-controls">
        <input type="text" id="" value="" name="post[is_lunch]" class="uk-width-1-1" placeholder="车型/颜色">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">车牌号</label>
      <div class="uk-form-controls">
        <input type="text" id="id_number" value="" name="post[id_number]" class="uk-width-1-1" placeholder="车牌号">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">缴费周期</label>
      <div class="uk-form-controls">
         <span class="id-pre uk-width-1-1">
           <select id="pre" name="post[is_car]">
             <option value="2024.04.01-2024.09.30">2024.04.01-2024.09.30</option>
             <option value="2024.04.01-2025.03.31">2024.04.01-2025.03.31</option>
          </select>
         </span>
      </div>
    </div>
-->

    <div class="uk-form-row">
      <label class="uk-form-label" for="">路线选择</label>
      <div class="uk-form-controls">
         <span class="id-pre uk-width-1-1">
           <select id="pre" name="post[is_car]">
             <option value="穿越深深庭院的私汤享受武义2日游">穿越深深庭院的私汤享受武义2日游</option>
             <option value="梦幻联动-上海迪士尼+海昌海洋公园2日游">梦幻联动-上海迪士尼+海昌海洋公园2日游</option>
             <option value="福建霞浦赶海4日游">福建霞浦赶海4日游</option>
             <option value="西宁青海湖4日游">西宁青海湖4日游</option>
             <option value="日本本州半自由6日游">日本本州半自由6日游</option>
             <option value="韩国济洲岛纯玩5日游">韩国济洲岛纯玩5日游</option>
          </select>
         </span>
      </div>
    </div>

    <!--<div class="uk-form-row">
      <label class="uk-form-label" for="">性别</label>
      <div class="uk-form-controls">
         <span class="id-pre uk-width-1-1">
           <select id="pre" name="post[is_attendance]">
             <option value="女">女</option>
             <option value="男">男</option>
          </select>
         </span>
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">已婚/未婚(男性可忽略)</label>
      <div class="uk-form-controls">
         <span class="id-pre uk-width-1-1">
           <select id="pre" name="post[is_lunch]">
             <option value=""></option>
             <option value="未婚">未婚</option>
             <option value="已婚">已婚</option>
          </select>
         </span>
      </div>
    </div>


    <div class="uk-form-row">
      <label class="uk-form-label" for="">联系方式</label>
      <div class="uk-form-controls">
        <input type="text" id="phone" value="" name="post[phone]" class="uk-width-1-1" placeholder="联系方式">
      </div>
    </div>



    -->


<!--
-->
    <div class="uk-form-row">
      <label class="uk-form-label" for="">备注</label>
      <div class="uk-form-controls">
        <textarea id="notes" cols="30" rows="5" placeholder="特殊需求请备注" class="uk-width-1-1" name="post[notes]"></textarea>
      </div>
    </div>


    <h3 class="tm-article-subtitle">家属<small>(点击加号添加家属)</small></h3>
    <div class="uk-form-row families-div">
       <!--<div class="uk-form-controls">
         <span class="id-pre uk-width-1-4">
           <select class="families_type" name="post[families][][type]">
             <option value="儿童">儿童</option>
             <option value="成人">成人</option>
          </select>
         </span>
         <input type="text" value="" name="post[families][][name]" class="uk-width-3-4" placeholder="请输入家属姓名">
         <input type="text" value="" name="post[families][][height]" class="uk-width-1-1" style="margin-top:5px;" placeholder="如果是儿童请输入身高(cm)">
         <input type="text" value="" name="post[families][][id_number]" class="uk-width-1-1" style="margin-top:5px;" placeholder="身份证号，请认真填写">
         <label for="">是否用午餐：</label>
           <select id="pre" name="post[families][][is_lunch]">
             <option value="用餐">用餐</option>
             <option value="不用餐">不用餐</option>
          </select>
         <br />
         <label for="">是否乘车：</label>
           <select id="pre" name="post[families][][is_car]">
             <option value="乘坐大巴">乘坐大巴</option>
             <option value="自驾">自驾</option>
           </select>
       </div>-->
    </div>

    <div class="uk-form-row">
      <button class="uk-button" id="btn_add" type="button">+</button>
      <button class="uk-button" id="btn_remove" type="button">-</button>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">
      <button class="uk-button uk-button-primary" id="btn_submit" type="submit">提交</button>
    </div>
  <% end %>
  <h3 class="tm-article-subtitle" style="color:red;">注意事项</h3>
  <ul class="uk-list uk-list-disc">
    <li>请用微信扫玛报名</li>
    <li>报名后不支持在线修改, 有问题请联系徐冯晓</li>
  </ul>
</div>
<!-- 之前_scripts中内容在这 -->

<script>
$(function(){
  var fn_btn_submit = function() {
    var username = $('#username').val();
    var phone    = $('#phone').val();
    var id_number    = $('#id_number').val();
    var inputs   = $(':input[name*="families"]');
    var submit_tag = true;
    inputs.each(function(){
      if ($(this).val() == '') {
        UIkit.notify('提交失败，家属信息填写不完整', {status:'warning'});
        submit_tag = false;
        return false;
      }
    });
    if (username == '') {
        UIkit.notify('姓名为空', {status:'warning'});
        return false;
    }
    if (phone == '') {
        UIkit.notify('电话为空', {status:'warning'});
        return false;
    }
    if (id_number == '') {
        UIkit.notify('身份证为空', {status:'warning'});
        return false;
    }
    return submit_tag;
  }

  var fn_btn_add = function() {
    var insert_html = '<div class="uk-form-row families_person">' +
       '<div class="uk-form-controls">' +
         '<span class="id-pre uk-width-1-4">' +
           '<select class="families_type" name="post[families][][type]">' +
             '<option value="儿童">儿童</option>' +
             '<option value="成人">成人</option>' +
          '</select>' +
         '</span>' +
         '<input type="text" value="" name="post[families][][name]" class="uk-width-3-4" placeholder="请输入家属姓名">' +
         '<input type="text" value="" name="post[families][][height]" class="uk-width-1-1" style="margin-top:5px;" placeholder="如果是儿童请输入身高(cm)">' +
         '<input type="text" value="" name="post[families][][id_number]" class="uk-width-1-1" style="margin-top:5px;" placeholder="身份证号，请认真填写">'+
       '</div>' +
    '</div>';
    $('.families-div').after(insert_html)
    $('.families_type').change(change_families_type);
  }

  var fn_btn_remove = function() {
    $('.families_person').first().remove();
  }

  $('#btn_submit').click(fn_btn_submit);
  $('#btn_add').click(fn_btn_add);
  $('#btn_remove').click(fn_btn_remove);

  var change_families_type = function() {
    if ($(this).val() == '成人') {
      $(this).parents().next().next().val('N/A');
    } else {
      $(this).parents().next().next().val('');
    }
  }
  $('.families_type').change(change_families_type);
});
</script>
<style type="text/css" media="screen">
  .tm-article-subtitle {
    padding-left: 6px;
    border-left: 3px solid #1FA2D6;
    font-size: 16px;
    line-height: 16px;
  }
</style>

app/views/register/index_displayer.html.erb
<% flash.each do |name, msg| %>
  <div class="uk-alert uk-alert-<%= name %>" data-uk-alert="">
    <a href="" class="uk-alert-close uk-close"></a>
    <p><%= msg %></p>
  </div>
<% end %>
<div class="register-box">
  <h1 class="title">显示器-请填写以下信息</h1>
  <%= form_for :register, url: user_lists_path, method: :post, html: { class: "uk-form uk-form-stacked" } do |f| %>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">姓名</label>
      <div class="uk-form-controls">
        <input type="text" id="username" value="" name="post[name]" class="uk-width-1-1" placeholder="请输入姓名">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">
      <button class="uk-button uk-button-primary" id="btn_submit" type="submit">提交，注册参加摇号</button>
      </label>
    </div>
  <% end %>
  <h3 class="tm-article-subtitle" style="color:red;">注意事项</h3>
  <ul class="uk-list">
    <li style="color:red;">显示器和电脑不能同时参加</li>
    <!--
    <li>2. 请用微信或者钉钉扫码报名。</li>
    <li>3. 报名截止时间本周日12点。</li>
    <li>4. 报名者要求：需要在公司服务半年以上，最近三次已经购买的同事本次不能参加，信息部有购买记录。</li>
    <li>5. 方式跟以前类似，通过摇号程序一次产生15个台式电脑的号码与电脑编号一一对应，依次选择电脑。</li>
    -->
  </ul>
  <!--
  <h3 class="tm-article-subtitle" style="color:red;">附件</h3>
  <ul class="uk-list">
    <li><a href="/dnxx.xlsx">电脑信息2020.9.27</a></li>
  </ul>
  -->
  <h3 class="tm-article-subtitle" style="color:red;">附件</h3>
  <ul class="uk-list">
    <li><a href="/bfdnxx.xlsx">显示器信息2021.5.21</a></li>
  </ul>
</div>
<!-- 之前_scripts中内容在这 -->

<script>
$(function(){
  var fn_btn_submit = function() {
    var username = $('#username').val();
    var phone    = $('#phone').val();
    var inputs   = $(':input[name*="families"]');
    var submit_tag = true;
    inputs.each(function(){
      if ($(this).val() == '') {
        UIkit.notify('提交失败，信息填写不完整', {status:'warning'});
        submit_tag = false;
        return false;
      }
    });
    if (username == '') {
        UIkit.notify('姓名为空', {status:'warning'});
        return false;
    }
    return submit_tag;
  }

  var fn_btn_add = function() {
    var insert_html = '<div class="uk-form-row families_person">' +
      '<label class="uk-form-label" for="">开户姓名</label>' +
       '<div class="uk-form-controls">' +
         '<input type="text" value="" name="post[families][][name]" class="uk-width-1-1" placeholder="请输入开户姓名">' +
       '</div>' +
       '<label class="uk-form-label" for="">手机号码</label>' +
       '<div class="uk-form-controls">' +
         '<input type="text" value="" name="post[families][][id_number]" class="uk-width-1-1" style="margin-top:5px;" placeholder="请输入手机号">' +
       '</div>' +
       '<label class="uk-form-label" for="">活动类型</label>' +
       '<div class="uk-form-controls">' +
        '<span class="id-pre uk-width-1-1">' +
          '<select id="pre" name="post[families][][type]">' +
            '<option value="两个都参加">两个都参加</option>' +
            '<option value="每月1G流量">每月1G流量</option>' +
            '<option value="每月100分钟通话">每月100分钟通话</option>' +
          '</select>' +
         '</span>' +
      '</div>' +
    '</div>';
    $('.families-div').after(insert_html)
    $('.families_type').change(change_families_type);
  }


  var fn_btn_remove = function() {
    $('.families_person').first().remove();
  }

  $('#btn_submit').click(fn_btn_submit);
  $('#btn_add').click(fn_btn_add);
  $('#btn_remove').click(fn_btn_remove);

  var change_families_type = function() {
    if ($(this).val() == '成人') {
      $(this).parents().next().next().val('N/A');
    } else {
      $(this).parents().next().next().val('');
    }
  }
  $('.families_type').change(change_families_type);
});
</script>
<style type="text/css" media="screen">
  .tm-article-subtitle {
    padding-left: 6px;
    border-left: 3px solid #1FA2D6;
    font-size: 16px;
    line-height: 16px;
  }
</style>

app/views/register/research_index.html.erb
<div class="register-box">
  <h1 class="title">查询报名结果</h1>
  <p>报名后系统会分配系统id，使用系统id和姓名才能查询报名结果</p>
  <%= form_for :register, url: research_users_path, method: :get, html: { class: "uk-form uk-form-stacked" } do |f| %>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">姓名</label>
      <div class="uk-form-controls">
        <input type="text" id="username" value="" name="post[username]" class="uk-width-1-1" placeholder="请输入报名时填写姓名">
      </div>
    </div>
    <div class="uk-form-row">
      <label class="uk-form-label" for="">系统id</label>
      <div class="uk-form-controls">
        <input type="text" id="user_id" value="" name="post[user_id]" class="uk-width-1-1" placeholder="系统id">
      </div>
    </div>

    <div class="uk-form-row">
      <label class="uk-form-label" for="">
      <button class="uk-button uk-button-primary" id="btn_submit" type="submit">点击查询</button>
      </label>
    </div>
  <% end %>
  <br />

  <a href="/"><<<返回</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<!-- 之前_scripts中内容在这 -->
<script>
$(function(){
  var fn_btn_submit = function() {
    var username = $('#username').val();
    var user_id = $('#user_id').val();
    if (username == '') {
        UIkit.notify('姓名为空', {status:'warning'});
        return false;
    }
    if (user_id == '') {
        UIkit.notify('系统id为空', {status:'warning'});
        return false;
    }
    return true;
  }

  $('#btn_submit').click(fn_btn_submit);

});
</script>
<style type="text/css" media="screen">
  .tm-article-subtitle {
    padding-left: 6px;
    border-left: 3px solid #1FA2D6;
    font-size: 16px;
    line-height: 16px;
  }
</style>